version: '3'
services: 
    tomcat:
        build:
            context: .
            dockerfile: ./tomcat/Dockerfile
        container_name: tomcat
        privileged: true
        ports:
            - "8012:8080"
        volumes:
            - "./tomcat/data:/var"
        tty: true
    jenkins:
        container_name: jenkins
        image: jenkins/jenkins
        ports:
            - "8888:8080"
        volumes: 
            - "./jenkins/data:/var/jenkins_home"
        tty: true
        links: 
            - tomcat